### ISSUE TITLE
Stuck on Liblzma

### ISSUE THREAD

**Issue by nbulischeck** [etrombly/gtk_osx_cross#1]
Any idea what to do to get past that last error? 

`clang: error: no such file or directory: '../../src/liblzma/.libs/liblzma.so'`

As you said in the readme, it creates the links but not the actual .so.

```
lrwxrwxrwx 1 root root     16 Jul 19 17:58 liblzma.so -> liblzma.so.5.2.4
lrwxrwxrwx 1 root root     16 Jul 19 17:58 liblzma.so.5 -> liblzma.so.5.2.4
```

**Comment by etrombly** [comment]
I never got past that point and gave up. Since AFAIK you need to sign GUI apps anyway it seemed easier to just build on a Mac.

**Comment by nbulischeck** [comment]
Hmm interesting; I've never heard that you had to sign GUI apps. I was just able to build liblzma.a which has a pkgconfig with:

```
git clone https://git.tukaani.org/xz.git

cd xz
git clean -dfx
./autogen.sh

sed -i -e 's|-m elf_x86_64||g' configure

CC="/usr/local/osx-ndk-x86/bin/x86_64-apple-darwin15-cc" \
OBJC="/usr/local/osx-ndk-x86/bin/x86_64-apple-darwin15-cc" \
CXX="/usr/local/osx-ndk-x86/bin/x86_64-apple-darwin15-c++" \
CFLAGS="-O2 -arch x86_64 -isysroot /usr/local/osx-ndk-x86/SDK/MacOSX10.11.sdk/ -mmacosx-version-min=10.7" \
LD="/usr/local/osx-ndk-x86/bin/x86_64-apple-darwin15-ld" \
AR="/usr/local/osx-ndk-x86/bin/x86_64-apple-darwin15-ar" \
AS="/usr/local/osx-ndk-x86/bin/x86_64-apple-darwin15-as" \
RANLIB="/usr/local/osx-ndk-x86/bin/x86_64-apple-darwin15-ranlib" \
NM="/usr/local/osx-ndk-x86/bin/x86_64-apple-darwin15-nm" \
STRIP="/usr/local/osx-ndk-x86/bin/x86_64-apple-darwin15-strip" \
./configure --prefix=/root/lzma --host=x86_64-unknown-linux-gnu --target=x86_64-apple-darwin --disable-shared --disable-xz --disable-xzdec --disable-lzmainfo --disable-scripts --disable-lzmadec

make -j2

make install
```

Though I'm not sure if it's feasible to compile all the dependencies and add them to the pkg-config path.

My goal was to have a Dockerfile for OSX, Windows, and Linux GTK3 compilation. Windows and Linux were dead simple, but OSX has been a pain in the ass.

**Comment by nbulischeck** [comment]
I'll close this for now as I have no plans to continue working on an OSX port.
